In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.stats.api as sms
from scipy import stats
import matplotlib.pyplot as plt
import plotly.express as px
import scipy
import seaborn as sns
import matplotlib.font_manager as fm
from sklearn.preprocessing import MinMaxScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
import math
import warnings
import pingouin as pg

Bad key text.latex.preview in file C:\Users\spa84\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 123 ('text.latex.preview : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key mathtext.fallback_to_cm in file C:\Users\spa84\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.jpeg_quality in file C:\Users\spa84\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key keymap.all_axes in file C:\Users\spa84\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.avconv_path in file C:\Users\spa84\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key animation.avconv_args in file C:\Users\spa84\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

In [2]:
warnings.simplefilter('ignore')

In [3]:
font_path = "C:\\Users\\spa84\\Downloads\\text_mining\\NanumGothic.ttf"  # 나눔 폰트의 경로를 지정
font_name = fm.FontProperties(fname=font_path).get_name()
plt.rc("font", family=font_name)

In [4]:
path = './data/'

df = pd.read_csv(path+'Coordinates_Preprocessed.csv')

In [5]:
df

,Building_Age,JS_Price,JS_BA,Population,UR,LC_index,CA_index,TC_index,SDT_index,HSP_index,Sell_Price,Crime_Rates,IR,Region_Name,Building_Use,YearMonth,Shortest_Distance_to_Subway,Shortest_Distance_to_School,Shortest_Distance_to_Univ,Shortest_Distance_to_Park
0,14,22500,84.70,433809,4.1,90.4,95.3,91.0,107.634598,91.7,39900.00,0.967620,1.25,강동구,아파트,201703,218.546662,342.320637,2080.047982,159.232767
1,0,16000,17.45,662019,3.4,98.0,101.1,99.1,112.039216,131.7,18000.00,0.834577,1.25,송파구,오피스텔,201912,365.167081,428.396368,2078.432085,1250.766345
2,30,42000,108.47,553927,2.7,78.0,84.3,81.7,120.439963,74.7,135000.00,1.537764,2.50,강남구,아파트,201310,698.127221,334.807784,1514.222790,918.048403
3,4,48000,84.95,674828,2.9,72.9,80.0,77.1,114.366829,79.4,91646.15,1.145652,3.25,송파구,아파트,201110,536.947700,24.176463,3817.518298,838.633151
4,0,70000,84.99,302243,2.1,109.0,109.0,110.3,87.677816,167.9,108000.00,0.725826,2.50,서대문구,아파트,202208,1173.890039,335.949816,1165.416466,701.477137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0,133000,84.86,530126,3.4,102.6,101.3,100.8,128.819696,158.1,193333.33,1.352069,0.50,강남구,아파트,202011,1341.605321,298.254673,3567.318940,1272.216183
4996,10,49000,84.91,427540,3.1,74.5,81.5,78.5,102.461258,74.2,81850.00,1.221012,3.00,서초구,아파트,201207,440.715060,269.506677,1053.568719,2804.609144
4997,0,23000,30.00,425539,4.5,93.9,98.0,94.1,94.786910,106.1,27038.00,0.907344,1.50,강동구,연립다세대,201803,364.897534,391.843327,1835.115994,251.807047
4998,0,71000,84.65,571614,3.8,106.9,103.8,103.4,117.233889,177.7,110000.00,0.671993,0.50,강서구,아파트,202106,0.000000,809.669099,2549.064034,864.197138
4999,4,34000,84.54,455617,3.6,84.1,88.5,86.5,120.617174,82.5,38666.67,0.884658,1.50,성북구,아파트,201507,586.255863,403.445394,1342.980946,995.127801

In [6]:
df.drop('YearMonth', axis=1, inplace=True)
df.drop('Region_Name', axis=1, inplace=True)
df.drop('Building_Use', axis=1, inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Building_Age                 5000 non-null   int64
 1   JS_Price                     5000 non-null   int64
 2   JS_BA                        5000 non-null   float64
 3   Population                   5000 non-null   int64
 4   UR                           5000 non-null   float64
 5   LC_index                     5000 non-null   float64
 6   CA_index                     5000 non-null   float64
 7   TC_index                     5000 non-null   float64
 8   SDT_index                    5000 non-null   float64
 9   HSP_index                    5000 non-null   float64
 10  Sell_Price                   5000 non-null   float64
 11  Crime_Rates                  5000 non-null   float64
 12  IR                           5000 non-null   float64
 13  Shortest_Distance_to_Subway  5000 non-null   float64
 14  Shortest_Distance_to_School  5000 non-null   float64
 15  Shortest_Distance_to_Univ    5000 non-null   float64
 16  Shortest_Distance_to_Park    5000 non-null   float64
dtypes: float64(14), int64(3)
memory usage: 664.2 KB

## Categorical:

- Nominal(variables that have two or more categories, but which do not have an intrinsic order.)

    - Region_Name : 자치구 명
    - Building_Use : 건물 용도
    
- Ordinal(variables that have two or more categories just like nominal variables. Only the categories can also be ordered or ranked.)

    
## Numeric:

- Discrete
    - YearMonth : 년월
    - Building_Age : 건물연식
    - JS_Price : 전세가
   
- Continous
    - Sell_Price : 매매 가격
    - JS_BA = JS_Building Area : 임대 면적
    - lR = Interest Rate : 금리
    - UR = Unemployment Rate : 실업률
    - LC_index = Leading Composite index : 선행종합 지수
    - CA_index = Comprehensive Accompany index : 동행종합 지수
    - TC_index = Trailing Composite index : 후행종합 지수
    - SDT_index = Supply and Demand Trend index = 전세수급동향 지수
    - HSP_index = 
    - Population : 인구수
    - Crime_Rates : 범죄율
    - Shortest_Distance_to_Subway : 가장 가까운 지하철역과의 거리
    - Shortest_Distance_to_School : 가장 가까운 초중고등학교와의 거리
    - Shortest_Distance_to_Univ : 가장 가까운 대학교와의 거리
    - Shortest_Distance_to_Park : 가장 가까운 공원과의 거리

## 데이터 전처리

### 이상치 제거

In [8]:
def detect_outliers(df, features_to_process):

    df_cleaned = df.copy()
    
    for feature in features_to_process:
        Q1 = df_cleaned[feature].quantile(0.25)
        Q3 = df_cleaned[feature].quantile(0.75)
        IQR = Q3 - Q1
        
        # IQR 범위 밖의 데이터를 이상치로 간주하고 제거
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df_cleaned = df_cleaned[(df_cleaned[feature] >= lower_bound) & (df_cleaned[feature] <= upper_bound)]
    
    return df_cleaned

In [9]:
df = detect_outliers(df, [df.columns])

In [10]:
df.dropna(inplace=True)

### 범주형 변수 인코딩

In [11]:
# 범주형 변수 더미화 함수, 범주형 변수의 범주 레벨 간의 관계가 중요할 시 사용
def oh_encoding(df):
    # DataFrame의 복사본을 만듭니다.
    df_encoded = df.copy()
    columns_encoded = []
    for column in df.columns:
        if df[column].dtype == object:
            df_encoded = pd.get_dummies(df_encoded, columns=[column], prefix=column)
            columns_encoded.append(column)
    return df_encoded, columns_encoded

In [12]:
df_encoded, columns_encoded = oh_encoding(df)

### 전체 변수 스케일링

In [13]:
# Min-Max 스케일러 생성
scaler = MinMaxScaler()

# 정규화할 열 선택 (수치형 데이터만, 원핫인코딩 열 제외)
numeric_columns = df_encoded.select_dtypes(include=['float', 'int']).columns
numeric_columns = [col for col in numeric_columns if col not in columns_encoded]

# 데이터 정규화
df_encoded[numeric_columns] = scaler.fit_transform(df_encoded[numeric_columns])

### 데이터프레임 수정

In [14]:
df_encoded

,Building_Age,JS_Price,JS_BA,Population,UR,LC_index,CA_index,TC_index,SDT_index,HSP_index,Sell_Price,Crime_Rates,IR,Shortest_Distance_to_Subway,Shortest_Distance_to_School,Shortest_Distance_to_Univ,Shortest_Distance_to_Park
0,0.294118,0.254762,0.622324,0.564466,0.714286,0.470588,0.532710,0.423174,0.547136,0.168385,0.209230,0.345980,0.250000,0.120316,0.524748,0.366461,0.052108
1,0.019608,0.175997,0.044028,0.976853,0.464286,0.664962,0.713396,0.627204,0.624175,0.512027,0.073864,0.236645,0.250000,0.201034,0.666722,0.366173,0.489341
2,0.607843,0.491057,0.826726,0.781525,0.214286,0.153453,0.190031,0.188917,0.771110,0.022337,0.797054,0.814526,0.666667,0.384338,0.512357,0.265577,0.356065
3,0.098039,0.563763,0.624473,1.000000,0.285714,0.023018,0.056075,0.073048,0.664887,0.062715,0.529079,0.492287,0.916667,0.295604,0.000000,0.676245,0.324254
4,0.019608,0.830352,0.624817,0.326719,0.000000,0.946292,0.959502,0.909320,0.198079,0.823024,0.630164,0.147273,0.666667,0.646258,0.514240,0.203386,0.269313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,0.058824,0.684940,0.624129,0.604691,0.178571,0.897698,0.844237,0.793451,0.415955,0.969931,0.874318,0.159998,0.166667,0.327932,0.272755,0.849554,0.192512
4993,0.411765,0.339586,0.404764,0.444056,0.535714,0.578005,0.629283,0.534005,0.383652,0.424399,0.413825,0.650895,0.333333,0.241688,0.633357,0.104522,0.296549
4994,0.431373,0.163880,0.392811,0.435426,0.428571,0.017903,0.040498,0.057935,0.630045,0.068729,0.125786,0.540569,0.916667,0.263848,0.433933,0.311553,0.079348
4997,0.019608,0.260821,0.151948,0.549521,0.857143,0.560102,0.616822,0.501259,0.322422,0.292096,0.129729,0.296445,0.333333,0.200886,0.606431,0.322791,0.089190
4999,0.098039,0.394116,0.620948,0.603874,0.535714,0.309463,0.320872,0.309824,0.774209,0.089347,0.201607,0.277802,0.333333,0.322749,0.625568,0.235045,0.386940

In [15]:
selected_columns = [
    'Shortest_Distance_to_Park',
    'LC_index',
    'TC_index',
    'SDT_index',
    'Sell_Price',
    'Building_Age',
    'IR',
    'HSP_index',
    'JS_BA',
    'Shortest_Distance_to_Subway',
    'CA_index',
    'JS_Price'
]

# 선택한 컬럼들만 남기기
df_encoded = df_encoded[selected_columns]

## Posthoc

In [16]:
posthoc = pg.pairwise_ttests(data=df_encoded, dv='JS_Price', parametric=False, padjust='fdr_bh', effsize='hedges')

RecursionError: maximum recursion depth exceeded while calling a Python object

In [ ]:
pg.print_table(posthoc, floatfmt='.3f')